// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH7tGO65msDJYYjwaQwWJVnHlvJc_i2QE',
    appId: '1:581450350799:web:04debad1e07493972137ba',
    messagingSenderId: '581450350799',
    projectId: 'mobiluygulama-a8b25',
    authDomain: 'mobiluygulama-a8b25.firebaseapp.com',
    storageBucket: 'mobiluygulama-a8b25.appspot.com',
    measurementId: 'G-B97ZWQHJD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEf76BV5KmfNuq1f8IsUihxlQMKYatrpY',
    appId: '1:581450350799:android:66e20ca514a7b8452137ba',
    messagingSenderId: '581450350799',
    projectId: 'mobiluygulama-a8b25',
    storageBucket: 'mobiluygulama-a8b25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjIH4ups8Sh3KgGfq4PXcpLRKkUIcHvws',
    appId: '1:581450350799:ios:e3a51aaf1cb433e12137ba',
    messagingSenderId: '581450350799',
    projectId: 'mobiluygulama-a8b25',
    storageBucket: 'mobiluygulama-a8b25.appspot.com',
    iosBundleId: 'com.example.mobilUygulama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjIH4ups8Sh3KgGfq4PXcpLRKkUIcHvws',
    appId: '1:581450350799:ios:bfdff2606c5b98ce2137ba',
    messagingSenderId: '581450350799',
    projectId: 'mobiluygulama-a8b25',
    storageBucket: 'mobiluygulama-a8b25.appspot.com',
    iosBundleId: 'com.example.mobilUygulama.RunnerTests',
  );
}
